[package]
name = "surface8"
version = "0.8.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ct-berry = { path = "../../ct-berry" }
utils = { path = "../utils" }
opencv = "0.88.7"